[project]
name = "neuracet-rag-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "numpy>=2.5.3",
    "ollama>=0.6.2",
    "sentence-transformers>=6.0.1",
    "uvicorn>=0.53.0",
]
